version: 0.2

phases:
  install:
    commands:
      - npm install
    finally:
      - echo finaliza instalacion
  build:
    commands:
      - npm run build
    finally:
      - echo finaliza construccion
