version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - pip install --upgrade awscli
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run start:prod
