export enum Configuration {
  PORT = 'PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  JWT_SECRET = 'JWT_SECRET',
  CLOUD_NAME = 'CLOUD_NAME',
  CLOUD_API_KEY = 'CLOUD_API_KEY',
  CLOUD_API_SECRET = 'CLOUD_API_SECRET',
  TYPEORM_SYNC = 'TYPEORM_SYNC',
}
